#pragma once

#define MAX_KEYBOARD_KEYS 350
#define MAX_LINE_LENGTH 1024

#define MAX_SOUND_CHANNELS 8
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define NUM_COLLECTABLES 10

#define PLAYER_SPEED 300
#define ADDED_SPEED_PER_LEVEL 10